----> Populacion de Puestos

INSERT INTO Puesto(Nombre,Descripcion) VALUES('Administrador','Empleado encargado de la administracion del negocio.');
INSERT INTO Puesto(Nombre,Descripcion) VALUES('Instructor','Empleado encargado de brindar asistencia a los clientes con el uso de las maquinas y creacion de rutinas.');
INSERT INTO Puesto(Nombre,Descripcion) VALUES('Dependiente Spa','Empleado encargado de la atencion de clientes dentro del spa.');
INSERT INTO Puesto(Nombre,Descripcion) VALUES('Dependiente Tienda','Empleado encargado de la atencion de clientes dentro de la tienda del gimnasio.');
INSERT INTO Puesto(Nombre,Descripcion) VALUES('Sin Asignar','Empleado sin un puesto asignado.');



----> Populacion de Planilla

INSERT INTO Planilla(Nombre,Descripcion) VALUES('Pago Mensual','Pago por labores realizadas a lo largo de un mes');
INSERT INTO Planilla(Nombre,Descripcion) VALUES('Pago por Horas','Pago por labores realizadas por horas a lo largo de un mes');
INSERT INTO Planilla(Nombre,Descripcion) VALUES('Pago por Clase','Pago por clases impartidas a lo largo de un mes.');
INSERT INTO Planilla(Nombre,Descripcion) VALUES('Sin Asignar ','Planilla sin asignar.');



----> Populacion de Equipos

INSERT INTO Tipo_Equipo(Nombre,Descripcion) VALUES('Cinta de Correr','Bandas electricas que permiten al usuario realizar ejercicios de atletismo de manera estatica');
INSERT INTO Tipo_Equipo(Nombre,Descripcion) VALUES('Bicicleta Estacionaria','Bicicletas elipticas que permiten realizar ejercicios de cardio');
INSERT INTO Tipo_Equipo(Nombre,Descripcion) VALUES('Multigimnasio','Estructura que incorpora multiples maquinas para realizar diferentes ejercicios ');
INSERT INTO Tipo_Equipo(Nombre,Descripcion) VALUES('Remos','Maquina diseñada para trabajar la zona de la espalda');
INSERT INTO Tipo_Equipo(Nombre,Descripcion) VALUES('Pesas','Mancuernas y otros equipos pra realizar ejercicios de levantamiento de peso');



----> Populacion de Servicios

INSERT INTO Tipo_Servicio(Nombre,Descripcion) VALUES('Indoor Cycling','Sesion de ciclismo en bicicletas elipticas con diferentes dificultades');
INSERT INTO Tipo_Servicio(Nombre,Descripcion) VALUES('Pilates','Sesion clasica de pilates guiada por un instructor');
INSERT INTO Tipo_Servicio(Nombre,Descripcion) VALUES('Yoga','Sesion de yoga guiada por un instructor con diferentes niveles de dificultad');
INSERT INTO Tipo_Servicio(Nombre,Descripcion) VALUES('Zumba','Sesion de baile aerobicos guiada por un instructor');
INSERT INTO Tipo_Servicio(Nombre,Descripcion) VALUES('Natacion','Sesion y clases de natacion guiadas por un instructor en la piscina del gimnasio');



----> Populacion de Tratamientos Spa

INSERT INTO Tratamiento_Spa(Nombre) VALUES('Masaje Relajante');
INSERT INTO Tratamiento_Spa(Nombre) VALUES('Masaje Descarga Muscular');
INSERT INTO Tratamiento_Spa(Nombre) VALUES('Sauna');
INSERT INTO Tratamiento_Spa(Nombre) VALUES('Baños a Vapor');



----> Populacion de Direcciones

INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Carmen');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Merced');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Hospital');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Catedral');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Zapote');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','San Francisco de Dos Ríos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Uruca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Mata Redonda');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Pavas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','Hatillo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','San José','San Sebastián');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Escazú','Escazú');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Escazú','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Escazú','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Desamparados');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','San Miguel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','San Juan de Dios');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','San Rafael Arriba');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Frailes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Patarrá');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','San Cristobal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Rosario');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Damas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','San Rafael Abajo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Gravilias');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Desamparados','Los Guido');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Santiago');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Mercedes Sur');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Barbacoas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Grifo Alto');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Candelarita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Desamparaditos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Puriscal','Chires');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tarrazú','San Marcos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tarrazú','San Lorenzo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tarrazú','San Carlos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','Aserrí');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','Tarbaca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','Vuelta de Jorco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','San Gabriel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','Legua');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','Monterrey');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Aserrí','Salitrillos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Colón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Guayabo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Tabarcia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Piedras Negras');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Picagres');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Jaris');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Mora','Quitirrisí');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','Guadalupe');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','San Francisco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','Calle Blancos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','Mata de Plátano');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','Ipís');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','Rancho Redondo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Goicoechea','Purral');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Santa Ana','Santa Ana');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Santa Ana','Salitral');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Santa Ana','Pozos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Santa Ana','Uruca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Santa Ana','Piedades');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Santa Ana','Brasil');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Alajuelita','Alajuelita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Alajuelita','San Josecito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Alajuelita','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Alajuelita','Concepción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Alajuelita','San Felipe');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Vázquez de Coronado','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Vázquez de Coronado','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Vázquez de Coronado','Dulce Nombre de Jesús');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Vázquez de Coronado','Patalillo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Vázquez de Coronado','Cascajal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Acosta','San Ignacio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Acosta','Guaitil');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Acosta','Palmichal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Acosta','Cangrejal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Acosta','Sabanillas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tibás','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tibás','Cinco Esquinas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tibás','Anselmo Llorente');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tibás','León XIII');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Tibás','Colima');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Moravia','San Vicente');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Moravia','San Jerónimo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Moravia','La Trinidad');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Montes de Oca','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Montes de Oca','Sabanilla');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Montes de Oca','Mercedes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Montes de Oca','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Turrubares','San Pablo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Turrubares','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Turrubares','San Juan de Mata');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Turrubares','San Luis');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Turrubares','Carara');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Dota','Santa María');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Dota','Jardín');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Dota','Copey');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Curridabat','Curridabat');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Curridabat','Granadilla');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Curridabat','Sánchez');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Curridabat','Tirrases');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','San Isidro de El General');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','El General');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Daniel Flores');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Rivas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Platanares');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Pejibaye');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Cajón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Barú');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Río Nuevo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','Páramo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','Pérez Zeledón','La Amistad');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','León Cortés','San Pablo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','León Cortés','San Andrés');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','León Cortés','Llano Bonito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','León Cortés','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','León Cortés','Santa Cruz');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('San José','León Cortés','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Alajuela');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','San José');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Carrizal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Guácima');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Sabanilla');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Río Segundo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Desamparados');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Turrúcares');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Tambor');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Garita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Alajuela','Sarapiquí');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','San Ramón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Santiago');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Piedades Norte');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Piedades Sur');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Ángeles');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Alfaro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Volio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Concepción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Zapotal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','Peñas Blancas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Ramón','San Lorenzo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','Grecia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','San José');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','San Roque');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','Tacares');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','Puente de Piedra');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Grecia','Bolívar');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Mateo','San Mateo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Mateo','Desmonte');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Mateo','Jesús María');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Mateo','Labrador');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','Atenas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','Jesús');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','Mercedes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','Concepción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','San José');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','Santa Eulalia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Atenas','Escobal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','Naranjo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','San Miguel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','San José');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','Cirrí Sur');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','San Jerónimo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','El Rosario');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Naranjo','Palmitos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','Palmares');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','Zaragoza');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','Buenos Aires');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','Santiago');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','Candelaria');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','Esquipulas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Palmares','La Granja');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Poás','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Poás','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Poás','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Poás','Carrillos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Poás','Sabana Redonda');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Orotina','Orotina');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Orotina','El Mastate');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Orotina','Hacienda Vieja');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Orotina','Coyolar');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Orotina','La Ceiba');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Quesada');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Florencia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Buenavista');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Aguas Zarcas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Venecia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Pital');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','La Fortuna');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','La Tigra');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','La Palmera');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Venado');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Cutris');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Monterrey');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','San Carlos','Pocosol');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Zarcero');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Laguna');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Tapesco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Guadalupe');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Palmira');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Zapote');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Zarcero','Brisas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Valverde Vega','Sarchí Norte');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Valverde Vega','Sarchí Sur');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Valverde Vega','Toro Amarillo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Valverde Vega','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Valverde Vega','Rodríguez');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Upala');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Aguas Claras');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','San José o Pizote');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Bijagua');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Delicias');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Dos Ríos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Yolillal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Upala','Canalete');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Los Chiles','Los Chiles');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Los Chiles','Caño Negro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Los Chiles','El Amparo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Los Chiles','San Jorge');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Guatuso','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Guatuso','Buenavista');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Guatuso','Cote');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Guatuso','Katira');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Río Cuarto','Río Cuarto');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Río Cuarto','Santa Rita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Alajuela','Río Cuarto','Santa Isabel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Oriental');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Occidental');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Carmen');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','San Nicolás');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Aguacaliente');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Guadalupe');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Corralillo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Tierra Blanca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Dulce Nombre');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Llano Grande');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Cartago','Quebradilla');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Paraíso','Paraíso');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Paraíso','Santiago');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Paraíso','Orosi');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Paraíso','Cachí');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Paraíso','Llanos de Santa Lucía');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','Tres Ríos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','San Diego');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','Concepción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','Dulce Nombre');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','San Ramón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','La Unión','Río Azul');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Jiménez','Juan Viñas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Jiménez','Tucurrique');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Jiménez','Pejibaye');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Turrialba');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','La Suiza');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Peralta');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Santa Cruz');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Santa Teresita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Pavones');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Tuis');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Tayutic');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Santa Rosa');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Tres Equis');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','La Isabel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Turrialba','Chirripó');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Alvarado','Pacayas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Alvarado','Cervantes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Alvarado','Capellades');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Oreamuno','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Oreamuno','Cot');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Oreamuno','Potrero Cerrado');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Oreamuno','Cipreses');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','Oreamuno','Santa Rosa');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','El Guarco','El Tejar');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','El Guarco','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','El Guarco','Tobosi');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Cartago','El Guarco','Patio de Agua');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Heredia','Heredia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Heredia','Mercedes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Heredia','San Francisco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Heredia','Ulloa');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Heredia','Varablanca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Barva','Barva');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Barva','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Barva','San Pablo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Barva','San Roque');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Barva','Santa Lucía');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Barva','San José de la Montaña');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','Santo Domingo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','San Vicente');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','San Miguel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','Paracito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','Santo Tomás');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','Santa Rosa');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','Tures');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santo Domingo','Pará');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santa Bárbara','Santa Bárbara');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santa Bárbara','San Pedro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santa Bárbara','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santa Bárbara','Jesús');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santa Bárbara','Santo Domingo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Santa Bárbara','Purabá');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Rafael','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Rafael','San Josecito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Rafael','Santiago');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Rafael','Ángeles');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Rafael','Concepción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Isidro','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Isidro','San José');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Isidro','Concepción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Isidro','San Francisco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Belén','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Belén','La Ribera');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Belén','La Asunción');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Flores','San Joaquín');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Flores','Barrantes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Flores','Llorente');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Pablo','San Pablo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','San Pablo','Rincón de Sabanilla');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Sarapiquí','Puerto Viejo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Sarapiquí','La Virgen');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Sarapiquí','Las Horquetas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Sarapiquí','Llanuras del Gaspar');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Heredia','Sarapiquí','Cureña');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Liberia','Liberia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Liberia','Cañas Dulces');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Liberia','Mayorga');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Liberia','Nacascolo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Liberia','Curubandé');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','Nicoya');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','Mansión');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','San Antonio');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','Quebrada Honda');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','Sámara');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','Nosara');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nicoya','Belén de Nosarita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Santa Cruz');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Bolsón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Veintisiete de Abril');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Tempate');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Cartagena');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Cuajiniquil');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Diriá');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Cabo Velas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Santa Cruz','Tamarindo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Bagaces','Bagaces');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Bagaces','La Fortuna');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Bagaces','Mogote');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Bagaces','Río Naranjo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Carrillo','Filadelfia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Carrillo','Palmira');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Carrillo','Sardinal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Carrillo','Belén');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Cañas','Cañas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Cañas','Palmira');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Cañas','San Miguel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Cañas','Bebedero');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Cañas','Porozal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Abangares','Las Juntas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Abangares','Sierra');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Abangares','San Juan');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Abangares','Colorado');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Tilarán');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Quebrada Grande');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Tronadora');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Santa Rosa');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Líbano');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Tierras Morenas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Cabeceras');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Tilarán','Arenal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nandayure','Carmona');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nandayure','Santa Rita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nandayure','Zapotal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nandayure','San Pablo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nandayure','Porvenir');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Nandayure','Bejuco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','La Cruz','La Cruz');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','La Cruz','Santa Cecilia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','La Cruz','La Garita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','La Cruz','Santa Elena');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Hojancha','Hojancha');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Hojancha','Monte Romo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Hojancha','Puerto Carrillo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Hojancha','Huacas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Guanacaste','Hojancha','Matambú');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Puntarenas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Pitahaya');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Chomes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Lepanto');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Paquera');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Manzanillo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Guacimal');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Barranca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Monte Verde');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Isla del Coco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Cóbano');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Chacarita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Chira');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Acapulco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','El Roble');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Puntarenas','Arancibia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Esparza','Espíritu Santo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Esparza','San Juan Grande');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Esparza','Macacona');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Esparza','San Rafael');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Esparza','San Jerónimo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Esparza','Caldera');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Buenos Aires');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Volcán');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Potrero Grande');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Boruca');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Pilas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Colinas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Chánguena');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Biolley');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Buenos Aires','Brunka');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Montes de Oro','Miramar');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Montes de Oro','La Unión');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Montes de Oro','San Isidro');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Osa','Puerto Cortés');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Osa','Palmar');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Osa','Sierpe');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Osa','Bahía Ballena');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Osa','Piedras Blancas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Osa','Bahía Drake');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Quepos','Quepos');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Quepos','Savegre');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Quepos','Naranjito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Golfito','Golfito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Golfito','Puerto Jiménez');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Golfito','Guaycará');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Golfito','Pavón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Coto Brus','San Vito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Coto Brus','Sabalito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Coto Brus','Agua Buena');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Coto Brus','Limoncito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Coto Brus','Pittier');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Coto Brus','Gutiérrez Braun');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Parrita','Parrita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Corredores','Corredor');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Corredores','La Cuesta');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Corredores','Canoas');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Corredores','Laurel');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Garabito','Jacó');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Puntarenas','Garabito','Tárcoles');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Limón','Limón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Limón','Valle La Estrella');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Limón','Río Blanco');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Limón','Matama');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','Guápiles');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','Jiménez');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','Rita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','Roxana');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','Cariari');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','Colorado');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Pococí','La Colonia');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','Siquirres');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','Pacuarito');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','Florida');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','Germania');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','El Cairo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','Alegría');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Siquirres','Reventazón');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Talamanca','Bratsi');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Talamanca','Sixaola');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Talamanca','Cahuita');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Talamanca','Telire');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Matina','Matina');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Matina','Batán');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Matina','Carrandi');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Guácimo','Guácimo');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Guácimo','Mercedes');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Guácimo','Pocora');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Guácimo','Río Jiménez');
INSERT INTO Direccion(Provincia,Canton,Distrito) VALUES('Limón','Guácimo','Duacarí');



